; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
board_build.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
build_flags =
    -DCAMERA_MODEL_ESP32S3_EYE
    -Wno-error=calloc-transposed-args
    -Wno-error=type-limits
    -Wno-error=header-guard
    -Wno-error=old-style-declaration
build_unflags =
    -fno-rtti
    -fuse-cxa-atexit
    -Wno-old-style-declaration
